### ISSUE TITLE
Add episodeBySlug query to GraphQL

### ISSUE THREAD

**Issue by lyle** [ttfkam/gs2021#20]
Probably just adding an index to the episode.slug in the db. 
I would be happy to see the PR on this so I know how to do similar things with changes to the db using squitch.

I need this for landing on Episode pages - which have the slug in the URL.

I will also be getting all episodes who's slug starts with "YYYY" and "YYYY/MM" for the year episode pages and month episode pages.

example https://geekspeak.org/episodes/2017/11/

**Comment by lyle** [comment]
I used this

```
-- Constraint: episode_slug_key

-- ALTER TABLE IF EXISTS public.episode DROP CONSTRAINT IF EXISTS episode_slug_key;

ALTER TABLE IF EXISTS public.episode
    ADD CONSTRAINT episode_slug_key UNIQUE (slug);
```

**Comment by ttfkam** [comment]
Closing the issue since we discussed using the airdate range instead.
